"""Write SHA-256 checksums for everything under data/ except empty keep-files."""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = ROOT / "checksums.txt"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    if not DATA.exists():
        print(f"missing {DATA}", file=sys.stderr)
        return 1

    rows: list[str] = []
    for path in sorted(DATA.rglob("*")):
        if not path.is_file():
            continue
        if path.name == ".gitkeep":
            continue
        rel = path.relative_to(ROOT).as_posix()
        rows.append(f"{sha256(path)}  {rel}")

    header = (
        "# SHA-256 of extracted originals in data/. Generated by tools/write_checksums.py.\n"
        "# Game files themselves are gitignored; this file is the stand-in.\n\n"
    )
    body = "\n".join(rows) + ("\n" if rows else "# (empty — no extracted files inventoried yet)\n")
    OUT.write_text(header + body, encoding="utf-8")
    print(f"wrote {len(rows)} checksums to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
